// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOh5UZbTU-4p_1SOQp75363N12xQMRk8',
    appId: '1:963557057878:web:b680aa8979739a0601a2f7',
    messagingSenderId: '963557057878',
    projectId: 'spms-13f8e',
    authDomain: 'spms-13f8e.firebaseapp.com',
    databaseURL: 'https://spms-13f8e-default-rtdb.firebaseio.com',
    storageBucket: 'spms-13f8e.appspot.com',
    measurementId: 'G-NFVDG3DVDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RHKdLPkKoR7Ri8ZSLRm_fbsKTDjG53E',
    appId: '1:963557057878:android:9b7fd7cbdc99acd401a2f7',
    messagingSenderId: '963557057878',
    projectId: 'spms-13f8e',
    databaseURL: 'https://spms-13f8e-default-rtdb.firebaseio.com',
    storageBucket: 'spms-13f8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN59SwttBJt8QOB9DDW0IJW-Mv6WXyzzk',
    appId: '1:963557057878:ios:1c42a87ff6f2acb601a2f7',
    messagingSenderId: '963557057878',
    projectId: 'spms-13f8e',
    databaseURL: 'https://spms-13f8e-default-rtdb.firebaseio.com',
    storageBucket: 'spms-13f8e.appspot.com',
    iosBundleId: 'com.example.zoomMeeting',
  );
}
